name: vili
description: مشروع كودو الخاص
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  telephony: ^0.2.0
  http: ^1.1.0
flutter:
  uses-material-design: true
