name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Kudo-App-Release
          path: build/app/outputs/flutter-apk/app-debug.apk
